// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

// 
//This source code was auto-generated by MonoXSD
//
namespace SimpleWebApi.Types {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="mh.dev.cb.01")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="mh.dev.cb.01", IsNullable=false)]
    public partial class CookBook {
        
        private Receipe[] receipesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Receipes")]
        public Receipe[] Receipes {
            get {
                return this.receipesField;
            }
            set {
                this.receipesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="mh.dev.cb.01")]
    public partial class Receipe {
        
        private int idField;
        
        private string codeField;
        
        private Ingredient[] ingredientsField;
        
        private string workflowField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Ingredients")]
        public Ingredient[] Ingredients {
            get {
                return this.ingredientsField;
            }
            set {
                this.ingredientsField = value;
            }
        }
        
        /// <remarks/>
        public string Workflow {
            get {
                return this.workflowField;
            }
            set {
                this.workflowField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="mh.dev.cb.01")]
    public partial class 
    Ingredient {
        
        private decimal quantityField;
        
        private UnitType unitField;
        
        private string nameField;
        
        /// <remarks/>
        public decimal Quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
            }
        }
        
        /// <remarks/>
        public UnitType Unit {
            get {
                return this.unitField;
            }
            set {
                this.unitField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="mh.dev.cb.01")]
    public enum UnitType {
        
        /// <remarks/>
        Stück,
        
        /// <remarks/>
        Gramm,
        
        /// <remarks/>
        Kilogramm,
        
        /// <remarks/>
        Liter,
        
        /// <remarks/>
        Milliliter,
    }
}
